name: 'Update Download Page and Create PR for alpha release'
description: 'Updated the download options after an alpha release is available'
inputs:
  version:
    description: 'The version of the alpha release'
    required: true
  DRI:
    description: 'The release DRIs github nick'
    required: true
  date:
    description: 'The release date'
    required: true
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true
jobs:
  update_and_create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Download README
        env:
          minorVersion: ${{ github.event.inputs.version }}
          releaseDate: ${{ github.event.inputs.date }}
        run: ./update-docs.sh

      - name: Create pull-request
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
          DRI: ${{ github.event.inputs.DRI }}
          GH_TOKEN: ${{ github.event.inputs.GITHUB_TOKEN }}
        run: ./create-pr.sh
